version: '3.3'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - '27019:27019'
    command: mongod
    volumes:
      - ./db:/data/db
  server:
    container_name: server
    restart: unless-stopped
    build: .
    ports:
      - '1234:1234'
    volumes:
        - /usr/src/app/node_modules
        - .:/usr/src/app
    links:
      - mongo
    environment:
      - API_URL=http://localhost:1234
      - PORT=1234
      - MONGO_URL = mongodb://mongo:27019/testdb
