version: "3"
services:
  mongo:
    container_name: mongo 
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    command: mongod
    volumes:
      - ./db:/data/db
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      - API_URL=http://localhost:4000
      - API_PORT=4000
      - DB = mongodb://mongo:27017/todolist
    